export const User = () => {
  return(
    <div>
      <h2>User5</h2>
      <div>
        <ul>
          <li>1</li>
          <li>2</li>
          <li>3</li>
        </ul>
      </div>
      <div>
        <ul>
          <li>4</li>
          <li>5</li>
          <li>6</li>
        </ul>
      </div>
      <div>
        <ul>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </div>
    </div>
  )
}